# Generated by Django 4.0 on 2021-12-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_product_testsequence_teststandard_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
