# Generated by Django 4.0 on 2021-12-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='postalCode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
