# Generated by Django 4.0 on 2021-12-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_location_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certNumber',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
