# Generated by Django 3.1.3 on 2022-01-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220101_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsequence',
            name='sequenceName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
