# Generated by Django 3.1.3 on 2022-01-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20220101_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancedata',
            name='maxSystemVoltage',
            field=models.IntegerField(null=True),
        ),
    ]
